name: Replace Code Blocks

on:
  push:
    branches:
      - main  # Hier den Namen deiner Haupt-Branch angeben

jobs:
  replace-code-blocks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Hier die gewünschte Python-Version angeben

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Replace Code Blocks
        run: |
          python scripts/skript.py  # Hier den Namen deines Python-Skripts angeben

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Replace code blocks" || echo "No changes to commit"
